# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Trabalho-2/PCPO/mult_matriz/mult_matriz.srcs/sources_1/ip/mu_2/mu_2.xci
# IP: The module: 'mu_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Trabalho-2/PCPO/mult_matriz/mult_matriz.srcs/sources_1/ip/mu_2/mu_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mu_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Trabalho-2/PCPO/mult_matriz/mult_matriz.srcs/sources_1/ip/mu_2/mu_2.xci
# IP: The module: 'mu_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Trabalho-2/PCPO/mult_matriz/mult_matriz.srcs/sources_1/ip/mu_2/mu_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mu_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
