# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Sistemas-Digitais/Trabalho-2/hls/solution_perfomance/solution_perfomance.srcs/sources_1/ip/matrixmul_0/matrixmul_0.xci
# IP: The module: 'matrixmul_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sistemas-Digitais/Trabalho-2/hls/solution_perfomance/solution_perfomance.gen/sources_1/ip/matrixmul_0/constraints/matrixmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrixmul_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Sistemas-Digitais/Trabalho-2/hls/solution_perfomance/solution_perfomance.srcs/sources_1/ip/matrixmul_0/matrixmul_0.xci
# IP: The module: 'matrixmul_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Sistemas-Digitais/Trabalho-2/hls/solution_perfomance/solution_perfomance.gen/sources_1/ip/matrixmul_0/constraints/matrixmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrixmul_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
