# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aluno/Desktop/SD/Sistemas-Digitais/memoria/memoria.srcs/sources_1/ip/mem_resposta/mem_resposta.xci
# IP: The module: 'mem_resposta' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aluno/Desktop/SD/Sistemas-Digitais/memoria/memoria.gen/sources_1/ip/mem_resposta/mem_resposta_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_resposta'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/aluno/Desktop/SD/Sistemas-Digitais/memoria/memoria.srcs/sources_1/ip/mem_resposta/mem_resposta.xci
# IP: The module: 'mem_resposta' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aluno/Desktop/SD/Sistemas-Digitais/memoria/memoria.gen/sources_1/ip/mem_resposta/mem_resposta_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_resposta'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
