# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.cache/wt [current_project]
set_property parent.project_path /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander.xci
set_property used_in_implementation false [get_files -all /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander.dcp]
set_property is_locked true [get_files /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander.xci]

synth_design -top mem_neander -part xc7vx485tffg1157-1 -mode out_of_context
rename_ref -prefix_all mem_neander_
write_checkpoint -noxdef mem_neander.dcp
catch { report_utilization -file mem_neander_utilization_synth.rpt -pb mem_neander_utilization_synth.pb }
if { [catch {
  file copy -force /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.runs/mem_neander_synth_1/mem_neander.dcp /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.ip_user_files/ip/mem_neander]} {
  catch { 
    file copy -force /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_stub.v /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.ip_user_files/ip/mem_neander
  }
}

if {[file isdir /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.ip_user_files/ip/mem_neander]} {
  catch { 
    file copy -force /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.srcs/sources_1/ip/mem_neander/mem_neander_stub.vhdl /media/juliana/LinFiles/Documents/GitHub/Sistemas-Digitais/Neander/Neander.ip_user_files/ip/mem_neander
  }
}
